### ISSUE TITLE
about  latency and Thrput

### ISSUE THREAD

**Issue by zzzhhh1031** [LeapLabTHU/AdaFocusV2#5]
Hello, thank you for your excellent work. Can you tell me how the latency and Thrput reported in the paper are calculated, and it has nothing to do with the dataset? Looking forward to your answers

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work. The practical speed is tested on an NVIDIA 3090 with bs=128 using our provided model. The basic procedure of benchmarking throughout is the same as: https://github.com/microsoft/Swin-Transformer/blob/main/main.py#L277 (In fact, this is the standard practice. I cite the code of Swin since it is quite elegant and easy-to-ready.)
